//lien quan toi path
export const CHANGE_PATH = 'CHANGE_PATH';
export const ROUTE_DEFAULT = 'ROUTE_DEFAULT';

//lien quan user
export const CHANGE_INFO_USER = 'CHANGE_INFO_USER';
export const CHANGE_DAILY_UPDATE = 'CHANGE_DAILY_UPDATE';
export const CHANGE_DAILY_HELPER = 'CHANGE_DAILY_HELPER';
export const CHANGE_DAILY_CARD_SELECT = 'CHANGE_DAILY_CARD_SELECT';
export const CHANGE_DELETECARD_CARD_SUCCESS = 'CHANGE_DELETECARD_CARD_SUCCESS';